name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: coursier/setup-action@v1
      with:
        jvm: 'adopt:11'
        sbt: '1.5.5'
    - name: Build project
      run: sbt compile
